### ISSUE TITLE
providing link to download obj files for items and scenes

### ISSUE THREAD

**Issue by monajalal** [owl-project/NVISII#161]
In order to be able to learn through your examples and be able to reproduce them to some extent, would you please be able to share links to examples of scene and 3d objects to download so we could run your examples?

Here are a few:

salle_de_bain_separated.obj
I tried searching for some of them but couldn't find them on Web. 

```
(nvisii) mona@ard-gpu-01:~/NVISII/examples$ python 08.obj_scene_loader.py 
Found 1 GPUs available for rendering.
Importing content/salle_de_bain_separated/salle_de_bain_separated.obj...
Traceback (most recent call last):
  File "/home/mona/NVISII/examples/08.obj_scene_loader.py", line 35, in <module>
    sdb = nvisii.import_scene(
  File "/home/mona/anaconda3/envs/nvisii/lib/python3.9/site-packages/nvisii/__init__.py", line 17171, in import_scene
    return _nvisii.import_scene(*args, **kwargs)
RuntimeError: Error: "content/salle_de_bain_separated/salle_de_bain_separated.obj"Unable to open file "content/salle_de_bain_separated/salle_de_bain_separated.obj".
CUDA call (cudaFree((void*)d_pointer)) failed with code 4 (line 94): driver shutting down
terminate called after throwing an instance of 'std::runtime_error'
  what():  fatal cuda error
Aborted (core dumped)


(nvisii) mona@ard-gpu-01:~/NVISII/examples$ python 06.textures.py 
Found 1 GPUs available for rendering.
Traceback (most recent call last):
  File "/home/mona/NVISII/examples/06.textures.py", line 36, in <module>
    dome = nvisii.texture.create_from_file("dome", "content/kiara_4_mid-morning_4k.hdr")
  File "/home/mona/anaconda3/envs/nvisii/lib/python3.9/site-packages/nvisii/__init__.py", line 18668, in create_from_file
    return _nvisii.texture_create_from_file(name, path, linear)
RuntimeError: Error: failed to load texture image "content/kiara_4_mid-morning_4k.hdr". Reason: can't fopen
CUDA call (cudaGetDevice(&savedActiveDeviceID)) failed with code 4 (line 145): driver shutting down
terminate called after throwing an instance of 'std::runtime_error'
  what():  fatal cuda error
Aborted (core dumped)

(nvisii) mona@ard-gpu-01:~/NVISII/examples$ python 09.meta_data_exporting.py 
created folder 09_metadata/
Found 1 GPUs available for rendering.
Warning: Could not do CUDA graphics resource sharing for the display buffer texture (unknown error)... falling back to slower path
Traceback (most recent call last):
  File "/home/mona/NVISII/examples/09.meta_data_exporting.py", line 71, in <module>
    brick_base_color = nvisii.texture.create_from_file("bricks_base_color", "./content/Bricks051_2K_Color.jpg")
  File "/home/mona/anaconda3/envs/nvisii/lib/python3.9/site-packages/nvisii/__init__.py", line 18668, in create_from_file
    return _nvisii.texture_create_from_file(name, path, linear)
RuntimeError: Error: failed to load texture image "./content/Bricks051_2K_Color.jpg". Reason: can't fopen
Segmentation fault (core dumped)


(nvisii) mona@ard-gpu-01:~/NVISII/examples$ python 11.instance_motion_blur.py 
Found 1 GPUs available for rendering.
Traceback (most recent call last):
  File "/home/mona/NVISII/examples/11.instance_motion_blur.py", line 51, in <module>
    mesh = nvisii.mesh.create_from_file("obj", opt.path_obj)
  File "/home/mona/anaconda3/envs/nvisii/lib/python3.9/site-packages/nvisii/__init__.py", line 21923, in create_from_file
    return _nvisii.mesh_create_from_file(name, path)
RuntimeError: Error: "obj"Unable to open file "content/dragon/dragon.obj".
CUDA call (cudaGetDevice(&savedActiveDeviceID)) failed with code 4 (line 145): driver shutting down
terminate called after throwing an instance of 'std::runtime_error'
  what():  fatal cuda error
Aborted (core dumped)

```

**Comment by TontonTremblay** [comment]
We provide a script to download the content used in the example, check https://github.com/owl-project/NVISII/blob/master/examples/download_content.sh
