### ISSUE TITLE
 return _nvisii.mesh_create_from_data(*args, **kwargs) RuntimeError: Error: No indices provided, and length of positions (7838688) is not a multiple of 3.

### ISSUE THREAD

**Issue by monajalal** [owl-project/NVISII#162]
I have been able to run all the examples up until 16 so I thought to report the package.
It is possible I have a different version of HW/SW causing this?

```
(nvisii) mona@ard-gpu-01:~/NVISII/examples$ pip freeze | grep nvisii
nvisii==1.1.72
(nvisii) mona@ard-gpu-01:~/NVISII/examples$ pip freeze | grep open3d
open3d==0.16.0
(nvisii) mona@ard-gpu-01:~/NVISII/examples$ python --version
Python 3.9.16
```

```
(nvisii) mona@ard-gpu-01:~/NVISII/examples$ python 16.create_mesh_from_data.py 
Found 1 GPUs available for rendering.
Traceback (most recent call last):
  File "/home/mona/NVISII/examples/16.create_mesh_from_data.py", line 53, in <module>
    mesh = nvisii.mesh.create_from_data(
  File "/home/mona/anaconda3/envs/nvisii/lib/python3.9/site-packages/nvisii/__init__.py", line 21960, in create_from_data
    return _nvisii.mesh_create_from_data(*args, **kwargs)
RuntimeError: Error: No indices provided, and length of positions (7838688) is not a multiple of 3.
CUDA call (cudaFree((void*)d_pointer)) failed with code 4 (line 94): driver shutting down
terminate called after throwing an instance of 'std::runtime_error'
  what():  fatal cuda error
Aborted (core dumped)
```

```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

```

$ uname -a
Linux ard-gpu-01 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

![Screenshot from 2023-01-19 14-33-22](https://user-images.githubusercontent.com/1892917/213542389-128de31a-456c-4c53-8d57-565495d65d1d.png)

**Comment by TontonTremblay** [comment]
I will look into the example today. Maybe o3d changed the behavior of loading a mesh. The logic is still the same though.
